// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"{{ cookiecutter.app_name }}/app/user/internal/biz"
	"{{ cookiecutter.app_name }}/app/user/internal/conf"
	"{{ cookiecutter.app_name }}/app/user/internal/data"
	"{{ cookiecutter.app_name }}/app/user/internal/server"
	"{{ cookiecutter.app_name }}/app/user/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	{{ cookiecutter.app_name }}Repo := data.New{{ cookiecutter.app_name_camel }}Repo(dataData, logger)
	{{ cookiecutter.app_name }}Usecase := biz.New{{ cookiecutter.app_name_camel }}Usecase({{ cookiecutter.app_name }}Repo, logger)
	{{ cookiecutter.app_name }}Service := service.New{{ cookiecutter.app_name_camel }}Service({{ cookiecutter.app_name }}Usecase)
	userService := service.NewUserService({{ cookiecutter.app_name }}Usecase)
	grpcServer := server.NewGRPCServer(confServer, {{ cookiecutter.app_name }}Service, userService, logger)
	httpServer := server.NewHTTPServer(confServer, {{ cookiecutter.app_name }}Service, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
